# ---------------------------------------
# Base image for node
FROM node:19-bullseye-slim as node_base

# ---------------------------------------
# Base image for runtime
FROM python:3.11-slim-bullseye as base

ENV TZ=Etc/UTC
WORKDIR /usr/src/app

# Install Redis
RUN apt-get update \
    && apt-get install -y curl wget gnupg cmake lsb-release build-essential dumb-init \
    && curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/redis.list \
    && apt-get update \
    && apt-get install -y redis \
    && apt-get clean \
    && mkdir -p /etc/redis /var/redis \
    && pip install --upgrade pip \
    && echo "appendonly yes" >> /etc/redis/redis.conf \
    && echo "dir /data/db/" >> /etc/redis/redis.conf

# ---------------------------------------
# Dev environment
FROM base as dev

# Set ENV
WORKDIR /usr/src/app
ENV NODE_ENV='development'

# Install node.js and npm packages
COPY --from=node_base /usr/local /usr/local
COPY scripts/dev.sh /usr/src/app/dev.sh
COPY ./web/package.json ./web/package-lock.json ./

RUN npm ci \
    && chmod 755 /usr/src/app/dev.sh

EXPOSE 8008
EXPOSE 9124
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/bin/bash", "-c", "/usr/src/app/dev.sh"]
