FROM ghcr.io/ggerganov/llama.cpp:light as builder 

RUN mv main llama

FROM ubuntu:latest
WORKDIR /usr/src/app

RUN apt update
RUN apt-get install -y python3-pip
RUN pip install --upgrade pip

COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY --from=builder /llama /usr/bin/llama