FROM gcc:10.2 as builder 

WORKDIR /tmp

RUN git clone https://github.com/ggerganov/llama.cpp.git --branch master-d5850c5

RUN cd llama.cpp && \
    make && \
    mv main llama

FROM ubuntu:latest
WORKDIR /usr/src/app

RUN apt update
RUN apt-get install -y python3-pip
RUN pip install --upgrade pip

COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY --from=builder /tmp/llama.cpp/llama /usr/bin/llama